# PostgreSQL. Versions 9.5 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: van_quote_development

test:
  <<: *default
  database: van_quote_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
